services:
  - type: web
    name: alrawasi-crm
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
